### PR TITLE
Limit input: Use VBF samples with dipole recoil

### PR DESCRIPTION
**Pull request by alpakpinar**
Hey @AndreasAlbert, I think this was somehow stuck in another branch and not merged into master. I just changed the regular expression for VBF signal so that we match the one with dipole recoil as well. With the current version, it matches both the non-DR and DR sample, is it possible to maybe move the non-DR 2018 sample to a temp/ directory on 03Sep20v7 so that we don't process that at all? What do you think? Thanks!

### CODE REVIEW

**Comment by alpakpinar** [comment]
Just pushed an additional commit to include the XS for the VBF DR 2018 sample

**Comment by AndreasAlbert** [comment]
wouldnt it make sense to just treat them as separate processes with separate names? That would mean having one regex matching the one with dipole recoil, and another one matching the one without. Then, whichever one we consider the default can map to "vbf", while the other one is translated into "vbf_dipoleRecoil" or "vbf_noDipole" or whatever. that seems to me more straighforwrad than moving input files around

**Comment by alpakpinar** [comment]
Thanks for the suggestion, that is indeed a much better way to do it. I'll try to modify the code so that we have to separate processes for two versions of the VBF samples, and we can specify a default and map it to "vbf".

**Comment by alpakpinar** [comment]
I pushed two commits for a first implementation of this. This seems to work fine for me, however I needed to make a patch for 2017 as we don't have DR samples there yet. So for 2018 I do "VBF with DR" --> "vbf" and for 2017, it becomes "VBF without DR" --> "vbf". Let me know what you think and if you want any changes to this, thanks a lot!

**Pull request merged**
