### PR TITLE
Add gen-tau checking for VBF

### PR DESCRIPTION
**Pull request by alpakpinar**
In this PR, the following tau check is introduced:

If there are one or more taus in the event, check if all taus match to a gen-level tau with "Tau_genPartFlav==5".

### CODE REVIEW

**Comment by AndreasAlbert** [comment]
Thanks for this, looks good to me! Only comment I have is to please make the use of gen matching configurable. In the way it is written here you also change monojet, which we do not want at this moment.

**Comment by alpakpinar** [comment]
Ah sorry its actually my bad, I modified the monojet processor quickly after seeing it fails the test, I'll make this configurable for both monojet and VBF in a new commit.

**Comment by alpakpinar** [comment]
Hey @AndreasAlbert , just pushed a new commit to make the gen-tau checking configurable in monojet and VBF. For monojet I set the default to False, while for VBF the default is set to True. Let me know if you want any more changes, thanks!

**Comment by AndreasAlbert** [comment]
Thanks for the update, looks good!

**Pull request merged**
