### PR TITLE
Implementation of latest jet ID SF

### PR DESCRIPTION
**Pull request by alpakpinar**
Hey @AndreasAlbert , this PR contains the implementation of the latest jet ID SF for VBF. Only for jets in endcap, we compute the weight as a function of jet pt, depending on whether the jet is in negative or positive eta region. Otherwise we assign a weight of 1. Let me know if you have any comments, thank you!

### CODE REVIEW

**Comment by alpakpinar** [comment]
I think I need to change the EM fraction cut so that it is also applied only for endcap jets to be consistent, sorry about that, will update shortly (and I guess we now somehow have a version conflict in our packages, all the tests failed)

**Comment by alpakpinar** [comment]
NEF<0.7 cut is also modified now: We require that only for endcap jets, instead of cutting for all jets. Also regarding the version conflict, I have a possible working solution in #313.

**Comment by AndreasAlbert** [comment]
Looks good. Shall I merge?

**Comment by alpakpinar** [comment]
Thanks, this should be good to merge.

**Pull request merged**
