### PR TITLE
add WvsTQCD variable to mono-v regions; add monov plotting script

### PR DESCRIPTION
**Pull request by siqiyyyy**

### CODE REVIEW

**Comment by siqiyyyy** [comment]
@AndreasAlbert I think we need to update the test file here. It doesn't have TvsQCD branch yet.

**Comment by AndreasAlbert** [comment]
I realize I'm still missing 2016 test files, which are now running. Will merge as soon as those are available.

**Comment by AndreasAlbert** [comment]
Finally got around to it in #185

**Comment by AndreasAlbert** [comment]
Could you rebase on the current master to chck that the tests now run?

**Comment by siqiyyyy** [comment]
Done

**Comment by AndreasAlbert** [comment]
Thank you!

**Pull request merged**
